[metadata]
name = noble_tls_plus
version = 1.0.0
author = Arshan
author_email = arshan@arshan.dev
description = A Python library that extends httpx with proxy management and retry mechanisms.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/arshansgithub/noble_tls_plus
project_urls =
    Bug Tracker = https://github.com/arshansgithub/noble_tls_plus/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.6
install_requires =
    noble_tls>=0.0.107
    loguru>=0.7.3